[package]
name = "rust_mls_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
openmls = "0.8.1"
openmls_rust_crypto = "0.5.1"
openmls_basic_credential = "0.5.0"
tls_codec = "0.4"
hex = "0.4"
openmls_traits = "0.5.0"
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.12"
