FROM golang:latest AS go-builder
ENV PATH="$PATH:$(go env GOPATH)/bin"
WORKDIR /build
COPY mls_server/ ./mls_server/
WORKDIR /build/mls_server
RUN go mod tidy
RUN go build -o /bin/server_app cmd/main.go



FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*

COPY --from=go-builder /bin/server_app /usr/local/bin/

EXPOSE 4713
CMD ["server_app"]
