// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEmpty) Reset() {
	*x = AgentEmpty{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEmpty) ProtoMessage() {}

func (x *AgentEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEmpty.ProtoReflect.Descriptor instead.
func (*AgentEmpty) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type AgentInitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BrokerUrl     string                 `protobuf:"bytes,2,opt,name=broker_url,json=brokerUrl,proto3" json:"broker_url,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInitReq) Reset() {
	*x = AgentInitReq{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInitReq) ProtoMessage() {}

func (x *AgentInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInitReq.ProtoReflect.Descriptor instead.
func (*AgentInitReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInitReq) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *AgentInitReq) GetBrokerUrl() string {
	if x != nil {
		return x.BrokerUrl
	}
	return ""
}

func (x *AgentInitReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type AgentSubscribeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vni           uint32                 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSubscribeReq) Reset() {
	*x = AgentSubscribeReq{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSubscribeReq) ProtoMessage() {}

func (x *AgentSubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSubscribeReq.ProtoReflect.Descriptor instead.
func (*AgentSubscribeReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSubscribeReq) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

type AgentUnsubscribeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vni           uint32                 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUnsubscribeReq) Reset() {
	*x = AgentUnsubscribeReq{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUnsubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUnsubscribeReq) ProtoMessage() {}

func (x *AgentUnsubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUnsubscribeReq.ProtoReflect.Descriptor instead.
func (*AgentUnsubscribeReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentUnsubscribeReq) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

type AgentKeyReadyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vni           uint32                 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentKeyReadyReq) Reset() {
	*x = AgentKeyReadyReq{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentKeyReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentKeyReadyReq) ProtoMessage() {}

func (x *AgentKeyReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentKeyReadyReq.ProtoReflect.Descriptor instead.
func (*AgentKeyReadyReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentKeyReadyReq) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

type AgentKeyReadyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentKeyReadyRes) Reset() {
	*x = AgentKeyReadyRes{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentKeyReadyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentKeyReadyRes) ProtoMessage() {}

func (x *AgentKeyReadyRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentKeyReadyRes.ProtoReflect.Descriptor instead.
func (*AgentKeyReadyRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentKeyReadyRes) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\f\n" +
	"\n" +
	"AgentEmpty\"k\n" +
	"\fAgentInitReq\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x1d\n" +
	"\n" +
	"broker_url\x18\x02 \x01(\tR\tbrokerUrl\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\"%\n" +
	"\x11AgentSubscribeReq\x12\x10\n" +
	"\x03vni\x18\x01 \x01(\rR\x03vni\"'\n" +
	"\x13AgentUnsubscribeReq\x12\x10\n" +
	"\x03vni\x18\x01 \x01(\rR\x03vni\"$\n" +
	"\x10AgentKeyReadyReq\x12\x10\n" +
	"\x03vni\x18\x01 \x01(\rR\x03vni\"-\n" +
	"\x10AgentKeyReadyRes\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady2\xf6\x01\n" +
	"\fAgentService\x12.\n" +
	"\x04Init\x12\x13.agent.AgentInitReq\x1a\x11.agent.AgentEmpty\x128\n" +
	"\tSubscribe\x12\x18.agent.AgentSubscribeReq\x1a\x11.agent.AgentEmpty\x12<\n" +
	"\vUnsubscribe\x12\x1a.agent.AgentUnsubscribeReq\x1a\x11.agent.AgentEmpty\x12>\n" +
	"\n" +
	"IsKeyReady\x12\x17.agent.AgentKeyReadyReq\x1a\x17.agent.AgentKeyReadyResB\tZ\a./protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_proto_goTypes = []any{
	(*AgentEmpty)(nil),          // 0: agent.AgentEmpty
	(*AgentInitReq)(nil),        // 1: agent.AgentInitReq
	(*AgentSubscribeReq)(nil),   // 2: agent.AgentSubscribeReq
	(*AgentUnsubscribeReq)(nil), // 3: agent.AgentUnsubscribeReq
	(*AgentKeyReadyReq)(nil),    // 4: agent.AgentKeyReadyReq
	(*AgentKeyReadyRes)(nil),    // 5: agent.AgentKeyReadyRes
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: agent.AgentService.Init:input_type -> agent.AgentInitReq
	2, // 1: agent.AgentService.Subscribe:input_type -> agent.AgentSubscribeReq
	3, // 2: agent.AgentService.Unsubscribe:input_type -> agent.AgentUnsubscribeReq
	4, // 3: agent.AgentService.IsKeyReady:input_type -> agent.AgentKeyReadyReq
	0, // 4: agent.AgentService.Init:output_type -> agent.AgentEmpty
	0, // 5: agent.AgentService.Subscribe:output_type -> agent.AgentEmpty
	0, // 6: agent.AgentService.Unsubscribe:output_type -> agent.AgentEmpty
	5, // 7: agent.AgentService.IsKeyReady:output_type -> agent.AgentKeyReadyRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
