// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Init_FullMethodName        = "/agent.AgentService/Init"
	AgentService_Subscribe_FullMethodName   = "/agent.AgentService/Subscribe"
	AgentService_Unsubscribe_FullMethodName = "/agent.AgentService/Unsubscribe"
	AgentService_IsKeyReady_FullMethodName  = "/agent.AgentService/IsKeyReady"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Init(ctx context.Context, in *AgentInitReq, opts ...grpc.CallOption) (*AgentEmpty, error)
	Subscribe(ctx context.Context, in *AgentSubscribeReq, opts ...grpc.CallOption) (*AgentEmpty, error)
	Unsubscribe(ctx context.Context, in *AgentUnsubscribeReq, opts ...grpc.CallOption) (*AgentEmpty, error)
	IsKeyReady(ctx context.Context, in *AgentKeyReadyReq, opts ...grpc.CallOption) (*AgentKeyReadyRes, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Init(ctx context.Context, in *AgentInitReq, opts ...grpc.CallOption) (*AgentEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentEmpty)
	err := c.cc.Invoke(ctx, AgentService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Subscribe(ctx context.Context, in *AgentSubscribeReq, opts ...grpc.CallOption) (*AgentEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentEmpty)
	err := c.cc.Invoke(ctx, AgentService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Unsubscribe(ctx context.Context, in *AgentUnsubscribeReq, opts ...grpc.CallOption) (*AgentEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentEmpty)
	err := c.cc.Invoke(ctx, AgentService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) IsKeyReady(ctx context.Context, in *AgentKeyReadyReq, opts ...grpc.CallOption) (*AgentKeyReadyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentKeyReadyRes)
	err := c.cc.Invoke(ctx, AgentService_IsKeyReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Init(context.Context, *AgentInitReq) (*AgentEmpty, error)
	Subscribe(context.Context, *AgentSubscribeReq) (*AgentEmpty, error)
	Unsubscribe(context.Context, *AgentUnsubscribeReq) (*AgentEmpty, error)
	IsKeyReady(context.Context, *AgentKeyReadyReq) (*AgentKeyReadyRes, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Init(context.Context, *AgentInitReq) (*AgentEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedAgentServiceServer) Subscribe(context.Context, *AgentSubscribeReq) (*AgentEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAgentServiceServer) Unsubscribe(context.Context, *AgentUnsubscribeReq) (*AgentEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedAgentServiceServer) IsKeyReady(context.Context, *AgentKeyReadyReq) (*AgentKeyReadyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method IsKeyReady not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Init(ctx, req.(*AgentInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSubscribeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Subscribe(ctx, req.(*AgentSubscribeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentUnsubscribeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Unsubscribe(ctx, req.(*AgentUnsubscribeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_IsKeyReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentKeyReadyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).IsKeyReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_IsKeyReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).IsKeyReady(ctx, req.(*AgentKeyReadyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _AgentService_Init_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _AgentService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _AgentService_Unsubscribe_Handler,
		},
		{
			MethodName: "IsKeyReady",
			Handler:    _AgentService_IsKeyReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
