// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mls.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_mls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{0}
}

type GenerateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq) Reset() {
	*x = GenerateReq{}
	mi := &file_mls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq) ProtoMessage() {}

func (x *GenerateReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq.ProtoReflect.Descriptor instead.
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GenerateKeyPackageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPackageHex string                 `protobuf:"bytes,1,opt,name=key_package_hex,json=keyPackageHex,proto3" json:"key_package_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyPackageRes) Reset() {
	*x = GenerateKeyPackageRes{}
	mi := &file_mls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyPackageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPackageRes) ProtoMessage() {}

func (x *GenerateKeyPackageRes) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPackageRes.ProtoReflect.Descriptor instead.
func (*GenerateKeyPackageRes) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyPackageRes) GetKeyPackageHex() string {
	if x != nil {
		return x.KeyPackageHex
	}
	return ""
}

type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_mls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type InviteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetKpHex   string                 `protobuf:"bytes,3,opt,name=target_kp_hex,json=targetKpHex,proto3" json:"target_kp_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteReq) Reset() {
	*x = InviteReq{}
	mi := &file_mls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteReq) ProtoMessage() {}

func (x *InviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteReq.ProtoReflect.Descriptor instead.
func (*InviteReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{4}
}

func (x *InviteReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InviteReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *InviteReq) GetTargetKpHex() string {
	if x != nil {
		return x.TargetKpHex
	}
	return ""
}

type InviteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WelcomeBytes  []byte                 `protobuf:"bytes,1,opt,name=welcome_bytes,json=welcomeBytes,proto3" json:"welcome_bytes,omitempty"`
	CommitBytes   []byte                 `protobuf:"bytes,2,opt,name=commit_bytes,json=commitBytes,proto3" json:"commit_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRes) Reset() {
	*x = InviteRes{}
	mi := &file_mls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRes) ProtoMessage() {}

func (x *InviteRes) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRes.ProtoReflect.Descriptor instead.
func (*InviteRes) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{5}
}

func (x *InviteRes) GetWelcomeBytes() []byte {
	if x != nil {
		return x.WelcomeBytes
	}
	return nil
}

func (x *InviteRes) GetCommitBytes() []byte {
	if x != nil {
		return x.CommitBytes
	}
	return nil
}

type ProcessCommitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CommitBytes   []byte                 `protobuf:"bytes,3,opt,name=commit_bytes,json=commitBytes,proto3" json:"commit_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCommitReq) Reset() {
	*x = ProcessCommitReq{}
	mi := &file_mls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCommitReq) ProtoMessage() {}

func (x *ProcessCommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCommitReq.ProtoReflect.Descriptor instead.
func (*ProcessCommitReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessCommitReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProcessCommitReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ProcessCommitReq) GetCommitBytes() []byte {
	if x != nil {
		return x.CommitBytes
	}
	return nil
}

type SerializeTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeTreeReq) Reset() {
	*x = SerializeTreeReq{}
	mi := &file_mls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeTreeReq) ProtoMessage() {}

func (x *SerializeTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeTreeReq.ProtoReflect.Descriptor instead.
func (*SerializeTreeReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{7}
}

func (x *SerializeTreeReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type SerializeTreeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeBytes     []byte                 `protobuf:"bytes,1,opt,name=tree_bytes,json=treeBytes,proto3" json:"tree_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializeTreeRes) Reset() {
	*x = SerializeTreeRes{}
	mi := &file_mls_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializeTreeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializeTreeRes) ProtoMessage() {}

func (x *SerializeTreeRes) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializeTreeRes.ProtoReflect.Descriptor instead.
func (*SerializeTreeRes) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{8}
}

func (x *SerializeTreeRes) GetTreeBytes() []byte {
	if x != nil {
		return x.TreeBytes
	}
	return nil
}

type JoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	WelcomeBytes  []byte                 `protobuf:"bytes,3,opt,name=welcome_bytes,json=welcomeBytes,proto3" json:"welcome_bytes,omitempty"`
	TreeBytes     []byte                 `protobuf:"bytes,4,opt,name=tree_bytes,json=treeBytes,proto3" json:"tree_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupReq) Reset() {
	*x = JoinGroupReq{}
	mi := &file_mls_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupReq) ProtoMessage() {}

func (x *JoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupReq.ProtoReflect.Descriptor instead.
func (*JoinGroupReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{9}
}

func (x *JoinGroupReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *JoinGroupReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupReq) GetWelcomeBytes() []byte {
	if x != nil {
		return x.WelcomeBytes
	}
	return nil
}

func (x *JoinGroupReq) GetTreeBytes() []byte {
	if x != nil {
		return x.TreeBytes
	}
	return nil
}

type ExportSecretReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSecretReq) Reset() {
	*x = ExportSecretReq{}
	mi := &file_mls_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSecretReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSecretReq) ProtoMessage() {}

func (x *ExportSecretReq) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSecretReq.ProtoReflect.Descriptor instead.
func (*ExportSecretReq) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{10}
}

func (x *ExportSecretReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExportSecretReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ExportSecretReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ExportSecretRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretBytes   []byte                 `protobuf:"bytes,1,opt,name=secret_bytes,json=secretBytes,proto3" json:"secret_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSecretRes) Reset() {
	*x = ExportSecretRes{}
	mi := &file_mls_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSecretRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSecretRes) ProtoMessage() {}

func (x *ExportSecretRes) ProtoReflect() protoreflect.Message {
	mi := &file_mls_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSecretRes.ProtoReflect.Descriptor instead.
func (*ExportSecretRes) Descriptor() ([]byte, []int) {
	return file_mls_proto_rawDescGZIP(), []int{11}
}

func (x *ExportSecretRes) GetSecretBytes() []byte {
	if x != nil {
		return x.SecretBytes
	}
	return nil
}

var File_mls_proto protoreflect.FileDescriptor

const file_mls_proto_rawDesc = "" +
	"\n" +
	"\tmls.proto\x12\x03mls\"\a\n" +
	"\x05Empty\"*\n" +
	"\vGenerateReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"?\n" +
	"\x15GenerateKeyPackageRes\x12&\n" +
	"\x0fkey_package_hex\x18\x01 \x01(\tR\rkeyPackageHex\"H\n" +
	"\x0eCreateGroupReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"g\n" +
	"\tInviteReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\"\n" +
	"\rtarget_kp_hex\x18\x03 \x01(\tR\vtargetKpHex\"S\n" +
	"\tInviteRes\x12#\n" +
	"\rwelcome_bytes\x18\x01 \x01(\fR\fwelcomeBytes\x12!\n" +
	"\fcommit_bytes\x18\x02 \x01(\fR\vcommitBytes\"m\n" +
	"\x10ProcessCommitReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12!\n" +
	"\fcommit_bytes\x18\x03 \x01(\fR\vcommitBytes\"-\n" +
	"\x10SerializeTreeReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"1\n" +
	"\x10SerializeTreeRes\x12\x1d\n" +
	"\n" +
	"tree_bytes\x18\x01 \x01(\fR\ttreeBytes\"\x8a\x01\n" +
	"\fJoinGroupReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12#\n" +
	"\rwelcome_bytes\x18\x03 \x01(\fR\fwelcomeBytes\x12\x1d\n" +
	"\n" +
	"tree_bytes\x18\x04 \x01(\fR\ttreeBytes\"_\n" +
	"\x0fExportSecretReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"4\n" +
	"\x0fExportSecretRes\x12!\n" +
	"\fsecret_bytes\x18\x01 \x01(\fR\vsecretBytes2\xc6\x03\n" +
	"\n" +
	"MlsService\x122\n" +
	"\x12GenerateCredential\x12\x10.mls.GenerateReq\x1a\n" +
	".mls.Empty\x12B\n" +
	"\x12GenerateKeyPackage\x12\x10.mls.GenerateReq\x1a\x1a.mls.GenerateKeyPackageRes\x12.\n" +
	"\vCreateGroup\x12\x13.mls.CreateGroupReq\x1a\n" +
	".mls.Empty\x12/\n" +
	"\rInviteMembers\x12\x0e.mls.InviteReq\x1a\x0e.mls.InviteRes\x122\n" +
	"\rProcessCommit\x12\x15.mls.ProcessCommitReq\x1a\n" +
	".mls.Empty\x12=\n" +
	"\rSerializeTree\x12\x15.mls.SerializeTreeReq\x1a\x15.mls.SerializeTreeRes\x12*\n" +
	"\tJoinGroup\x12\x11.mls.JoinGroupReq\x1a\n" +
	".mls.Empty\x12@\n" +
	"\x12ExportSharedSecret\x12\x14.mls.ExportSecretReq\x1a\x14.mls.ExportSecretResB\tZ\a./protob\x06proto3"

var (
	file_mls_proto_rawDescOnce sync.Once
	file_mls_proto_rawDescData []byte
)

func file_mls_proto_rawDescGZIP() []byte {
	file_mls_proto_rawDescOnce.Do(func() {
		file_mls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_proto_rawDesc), len(file_mls_proto_rawDesc)))
	})
	return file_mls_proto_rawDescData
}

var file_mls_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mls_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: mls.Empty
	(*GenerateReq)(nil),           // 1: mls.GenerateReq
	(*GenerateKeyPackageRes)(nil), // 2: mls.GenerateKeyPackageRes
	(*CreateGroupReq)(nil),        // 3: mls.CreateGroupReq
	(*InviteReq)(nil),             // 4: mls.InviteReq
	(*InviteRes)(nil),             // 5: mls.InviteRes
	(*ProcessCommitReq)(nil),      // 6: mls.ProcessCommitReq
	(*SerializeTreeReq)(nil),      // 7: mls.SerializeTreeReq
	(*SerializeTreeRes)(nil),      // 8: mls.SerializeTreeRes
	(*JoinGroupReq)(nil),          // 9: mls.JoinGroupReq
	(*ExportSecretReq)(nil),       // 10: mls.ExportSecretReq
	(*ExportSecretRes)(nil),       // 11: mls.ExportSecretRes
}
var file_mls_proto_depIdxs = []int32{
	1,  // 0: mls.MlsService.GenerateCredential:input_type -> mls.GenerateReq
	1,  // 1: mls.MlsService.GenerateKeyPackage:input_type -> mls.GenerateReq
	3,  // 2: mls.MlsService.CreateGroup:input_type -> mls.CreateGroupReq
	4,  // 3: mls.MlsService.InviteMembers:input_type -> mls.InviteReq
	6,  // 4: mls.MlsService.ProcessCommit:input_type -> mls.ProcessCommitReq
	7,  // 5: mls.MlsService.SerializeTree:input_type -> mls.SerializeTreeReq
	9,  // 6: mls.MlsService.JoinGroup:input_type -> mls.JoinGroupReq
	10, // 7: mls.MlsService.ExportSharedSecret:input_type -> mls.ExportSecretReq
	0,  // 8: mls.MlsService.GenerateCredential:output_type -> mls.Empty
	2,  // 9: mls.MlsService.GenerateKeyPackage:output_type -> mls.GenerateKeyPackageRes
	0,  // 10: mls.MlsService.CreateGroup:output_type -> mls.Empty
	5,  // 11: mls.MlsService.InviteMembers:output_type -> mls.InviteRes
	0,  // 12: mls.MlsService.ProcessCommit:output_type -> mls.Empty
	8,  // 13: mls.MlsService.SerializeTree:output_type -> mls.SerializeTreeRes
	0,  // 14: mls.MlsService.JoinGroup:output_type -> mls.Empty
	11, // 15: mls.MlsService.ExportSharedSecret:output_type -> mls.ExportSecretRes
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_mls_proto_init() }
func file_mls_proto_init() {
	if File_mls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_proto_rawDesc), len(file_mls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mls_proto_goTypes,
		DependencyIndexes: file_mls_proto_depIdxs,
		MessageInfos:      file_mls_proto_msgTypes,
	}.Build()
	File_mls_proto = out.File
	file_mls_proto_goTypes = nil
	file_mls_proto_depIdxs = nil
}
