// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: mls.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MlsService_GenerateCredential_FullMethodName = "/mls.MlsService/GenerateCredential"
	MlsService_GenerateKeyPackage_FullMethodName = "/mls.MlsService/GenerateKeyPackage"
	MlsService_CreateGroup_FullMethodName        = "/mls.MlsService/CreateGroup"
	MlsService_InviteMembers_FullMethodName      = "/mls.MlsService/InviteMembers"
	MlsService_ProcessCommit_FullMethodName      = "/mls.MlsService/ProcessCommit"
	MlsService_SerializeTree_FullMethodName      = "/mls.MlsService/SerializeTree"
	MlsService_JoinGroup_FullMethodName          = "/mls.MlsService/JoinGroup"
	MlsService_ExportSharedSecret_FullMethodName = "/mls.MlsService/ExportSharedSecret"
)

// MlsServiceClient is the client API for MlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MlsServiceClient interface {
	GenerateCredential(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*Empty, error)
	GenerateKeyPackage(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*GenerateKeyPackageRes, error)
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*Empty, error)
	InviteMembers(ctx context.Context, in *InviteReq, opts ...grpc.CallOption) (*InviteRes, error)
	ProcessCommit(ctx context.Context, in *ProcessCommitReq, opts ...grpc.CallOption) (*Empty, error)
	SerializeTree(ctx context.Context, in *SerializeTreeReq, opts ...grpc.CallOption) (*SerializeTreeRes, error)
	JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*Empty, error)
	ExportSharedSecret(ctx context.Context, in *ExportSecretReq, opts ...grpc.CallOption) (*ExportSecretRes, error)
}

type mlsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMlsServiceClient(cc grpc.ClientConnInterface) MlsServiceClient {
	return &mlsServiceClient{cc}
}

func (c *mlsServiceClient) GenerateCredential(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MlsService_GenerateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) GenerateKeyPackage(ctx context.Context, in *GenerateReq, opts ...grpc.CallOption) (*GenerateKeyPackageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKeyPackageRes)
	err := c.cc.Invoke(ctx, MlsService_GenerateKeyPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MlsService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) InviteMembers(ctx context.Context, in *InviteReq, opts ...grpc.CallOption) (*InviteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteRes)
	err := c.cc.Invoke(ctx, MlsService_InviteMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) ProcessCommit(ctx context.Context, in *ProcessCommitReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MlsService_ProcessCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) SerializeTree(ctx context.Context, in *SerializeTreeReq, opts ...grpc.CallOption) (*SerializeTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SerializeTreeRes)
	err := c.cc.Invoke(ctx, MlsService_SerializeTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MlsService_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlsServiceClient) ExportSharedSecret(ctx context.Context, in *ExportSecretReq, opts ...grpc.CallOption) (*ExportSecretRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSecretRes)
	err := c.cc.Invoke(ctx, MlsService_ExportSharedSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlsServiceServer is the server API for MlsService service.
// All implementations must embed UnimplementedMlsServiceServer
// for forward compatibility.
type MlsServiceServer interface {
	GenerateCredential(context.Context, *GenerateReq) (*Empty, error)
	GenerateKeyPackage(context.Context, *GenerateReq) (*GenerateKeyPackageRes, error)
	CreateGroup(context.Context, *CreateGroupReq) (*Empty, error)
	InviteMembers(context.Context, *InviteReq) (*InviteRes, error)
	ProcessCommit(context.Context, *ProcessCommitReq) (*Empty, error)
	SerializeTree(context.Context, *SerializeTreeReq) (*SerializeTreeRes, error)
	JoinGroup(context.Context, *JoinGroupReq) (*Empty, error)
	ExportSharedSecret(context.Context, *ExportSecretReq) (*ExportSecretRes, error)
	mustEmbedUnimplementedMlsServiceServer()
}

// UnimplementedMlsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMlsServiceServer struct{}

func (UnimplementedMlsServiceServer) GenerateCredential(context.Context, *GenerateReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCredential not implemented")
}
func (UnimplementedMlsServiceServer) GenerateKeyPackage(context.Context, *GenerateReq) (*GenerateKeyPackageRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateKeyPackage not implemented")
}
func (UnimplementedMlsServiceServer) CreateGroup(context.Context, *CreateGroupReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedMlsServiceServer) InviteMembers(context.Context, *InviteReq) (*InviteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMembers not implemented")
}
func (UnimplementedMlsServiceServer) ProcessCommit(context.Context, *ProcessCommitReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessCommit not implemented")
}
func (UnimplementedMlsServiceServer) SerializeTree(context.Context, *SerializeTreeReq) (*SerializeTreeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SerializeTree not implemented")
}
func (UnimplementedMlsServiceServer) JoinGroup(context.Context, *JoinGroupReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedMlsServiceServer) ExportSharedSecret(context.Context, *ExportSecretReq) (*ExportSecretRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSharedSecret not implemented")
}
func (UnimplementedMlsServiceServer) mustEmbedUnimplementedMlsServiceServer() {}
func (UnimplementedMlsServiceServer) testEmbeddedByValue()                    {}

// UnsafeMlsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MlsServiceServer will
// result in compilation errors.
type UnsafeMlsServiceServer interface {
	mustEmbedUnimplementedMlsServiceServer()
}

func RegisterMlsServiceServer(s grpc.ServiceRegistrar, srv MlsServiceServer) {
	// If the following call panics, it indicates UnimplementedMlsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MlsService_ServiceDesc, srv)
}

func _MlsService_GenerateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).GenerateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_GenerateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).GenerateCredential(ctx, req.(*GenerateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_GenerateKeyPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).GenerateKeyPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_GenerateKeyPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).GenerateKeyPackage(ctx, req.(*GenerateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_InviteMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).InviteMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_InviteMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).InviteMembers(ctx, req.(*InviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_ProcessCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).ProcessCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_ProcessCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).ProcessCommit(ctx, req.(*ProcessCommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_SerializeTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerializeTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).SerializeTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_SerializeTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).SerializeTree(ctx, req.(*SerializeTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).JoinGroup(ctx, req.(*JoinGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MlsService_ExportSharedSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).ExportSharedSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MlsService_ExportSharedSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).ExportSharedSecret(ctx, req.(*ExportSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MlsService_ServiceDesc is the grpc.ServiceDesc for MlsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MlsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mls.MlsService",
	HandlerType: (*MlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCredential",
			Handler:    _MlsService_GenerateCredential_Handler,
		},
		{
			MethodName: "GenerateKeyPackage",
			Handler:    _MlsService_GenerateKeyPackage_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _MlsService_CreateGroup_Handler,
		},
		{
			MethodName: "InviteMembers",
			Handler:    _MlsService_InviteMembers_Handler,
		},
		{
			MethodName: "ProcessCommit",
			Handler:    _MlsService_ProcessCommit_Handler,
		},
		{
			MethodName: "SerializeTree",
			Handler:    _MlsService_SerializeTree_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _MlsService_JoinGroup_Handler,
		},
		{
			MethodName: "ExportSharedSecret",
			Handler:    _MlsService_ExportSharedSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls.proto",
}
